version: "3.8"
services:
  ansible-server:
    container_name: ansible-server
    hostname: ansible-server
    build: 
      context: .
      dockerfile: ansible-alpine.Dockerfile
    volumes:
      - ../playbooks:/root/playground/playbooks
      - ../vars:/root/playground/vars
      - ../roles:/root/playground/roles
      - ../hosts:/root/playground/hosts
      - ../config:/root/playground/config
      - ../deploy:/root/playground/deploy
      - ../vault.yml:/root/playground/vault.yml
      - ../.vault_password:/root/playground/.vault_password
    networks: 
      - ansible

  slave1:
    cap_add:
      - NET_ADMIN
    container_name: slave1
    hostname: slave1
    volumes:
      - /sys/fs/cgroup
    build:
      context: .
      dockerfile: ansible-alpine.Dockerfile
    networks: 
      - ansible

  slave2:
    cap_add:
      - NET_ADMIN
    container_name: slave2
    hostname: slave2
    build: 
      context: .
      dockerfile: ansible-alpine.Dockerfile
    networks: 
      - ansible
      
  nginx-server:
    cap_add:
      - NET_ADMIN
    container_name: nginx-server
    hostname: nginx-server
    volumes:
      - /sys/fs/cgroup
    build:
      context: .
      dockerfile: ansible-alpine.Dockerfile
    networks: 
      - ansible

networks:
  ansible:
    driver: bridge
    

