version: "3.8"
services:
  ansible-server:
    container_name: ansible-server
    hostname: ansible-server
    build: 
      context: .
      dockerfile: ansible-alpine.Dockerfile
    volumes:
      - ../playbooks:/root/playground/playbooks
      - ../vars:/root/playground/vars
      - ../roles:/root/playground/roles
      - ../hosts:/root/playground/hosts
      - ../config:/root/playground/config
      - ../deploy:/root/playground/deploy
    networks: 
      - ansible
  slave1:
    container_name: slave1
    hostname: slave1
    build:
      context: .
      dockerfile: ansible-alpine.Dockerfile
    networks: 
      - ansible
  # slave2:
  #   container_name: slave2
  #   build: 
  #     context: .
  #     dockerfile: ansible-alpine.Dockerfile
  #   networks: 
  #     - ansible

networks:
  ansible:
    driver: bridge
    

