---
- name: create scripts directory
  file:
    path: /opt/nginx
    state: directory
  become: yes

- name: create nginx pid directory
  file:
    path: /run/nginx
    state: directory
  become: yes

- name: copy installation script for nginx
  become: yes
  template:
    src: install.sh.j2
    dest: /opt/nginx/install.sh
    mode: 0744

- name: copy network template
  become: yes
  template:
    src: network_config.j2
    dest: /etc/network/interfaces
    mode: 0744

- name: install nginx
  become: yes
  shell: /opt/nginx/install.sh

- name: copy nginx config template
  become: yes
  template:
    src: nginx_config.j2
    dest: /etc/nginx/nginx.conf
    mode: 0744

- name: enable nginx service
  become: yes
  service:
    name: nginx
    enabled: yes 

- name: start nginx service
  become: yes
  service:
    name: nginx
    state: started
  register: restart_nginx_svc